# Generated by Django 2.0.6 on 2021-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usdt', models.IntegerField()),
                ('description', models.TextField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
